trigger:
  tags:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-16.04'

variables:
  dockerId: cryptid
  imageName: cryptid-build-image

steps:
- script: |
    cd docker/cryptid-build-image
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(loginId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    loginId: $(dockerHubBotId)
    pswd: $(dockerHubBotPassword)
