trigger:
   branches:
    include:
      - refs/tags/*

jobs:
  - job: Build_container
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-16.04'

    variables:
      dockerId: cryptid
      imageName: cryptid-build-image

    steps:
    - script: |
        cd docker/cryptid-build-image
        docker build --privileged -t $(dockerId)/$(imageName):${IMAGE_TAG} .
        docker login -u ${loginId} -p ${pswd}
        docker push $(dockerId)/$(imageName):${IMAGE_TAG}
      env:
        IMAGE_TAG: $(Build.SourceBranchName)
        loginId: $(dockerHubBotId)
        pswd: $(dockerHubBotPassword)
